name: Push
on:
  push:
    branches-ignore:
      - main
jobs:
  release:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install, Lint, Test
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm build
